### ISSUE TITLE
Internet disconnection not detected

### ISSUE THREAD

**Issue by rsclmumbai** [ryvan-js/wiremonkey#1]
I tried this library.
Network connection break is detected immediately.
Internet connection break is not detected at all.
Works similar to navigator.onLine which has a similar behaviour.
_“online” does not always mean connection to the internet, it can also just mean connection to some network._

**Comment by ryvan-js** [comment]
Hello there,
Thanks for giving the plugin a try, yes i agree with you. Well the plugin uses two methods to detect the network/internet connection, the Image object (made for older browsers) and navigator object. The first method will able to tell you if it is actually connected to the internet on top of network connection. However by default the plugin always will try to use the navigator object to determine the connection if the navigator object is supported by the browser,but you can force the plugin to use the Image method by making a tiny change in the code.

Line 64:
if(typeof navigator === "object" && typeof navigator.onLine === "boolean"){
to
if(typeof navigator != "object" && typeof navigator.onLine === "boolean"){

This is just a temporary fix and this issue will be resolved in the next release.thank you :)
